### ISSUE TITLE
No 'tfm_gen' when trying to run feature extraction for vqa mcan

### ISSUE THREAD

**Issue by fallcat** [clip-vil/CLIP-ViL#29]
Hi! I'm trying to run mcan feature extraction.

This is the command I was trying to run: `python mcan_clip_grid_feature.py --config-file configs/R-50-grid.yaml --dataset coco_2014_train --model_type RN50`. And I got the following error. I searched throughout the codebase and didn't find where `self.tfm_gen` is defined.

```
Traceback (most recent call last):
  File "mcan_clip_grid_feature.py", line 142, in <module>
    main(args)
  File "mcan_clip_grid_feature.py", line 136, in main
    do_feature_extraction(cfg, model, args.dataset, args)
  File "mcan_clip_grid_feature.py", line 78, in do_feature_extraction
    extract_clip_feature_on_dataset(model, data_loader, dump_folder, args)
  File "mcan_clip_grid_feature.py", line 113, in extract_clip_feature_on_dataset
    for idx, inputs in enumerate(tqdm.tqdm(data_loader)):
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/tqdm/std.py", line 1133, in __iter__
    for obj in iterable:
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/detectron2/data/common.py", line 90, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/nlp/data/weiqiuy/miniconda3/envs/mmf/lib/python3.7/site-packages/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/mnt/nlpgridio3/data/weiqiuy/CLIP-ViL/CLIP-ViL-Direct/vqa/grid_feats/dataset_mapper.py", line 107, in __call__
    self.tfm_gens = [self.tfm_gens[0]] + [T.Resize((600, 1000))]
AttributeError: 'AttributeDatasetMapper' object has no attribute 'tfm_gens'
```

**Comment by fallcat** [comment]
solved by `python -m pip install 'git+https://github.com/facebookresearch/detectron2.git@ffff8ac'`

**Comment by bingninghuang** [comment]
Hi, I have also encounter this problem, but now the version ffff8ac is not correct. And I search in the website: https://github.com/facebookresearch/detectron2/releases that the newest version is V6.0 so I download this version. But similar error occurs again:
AttributeError: module 'PIL.Image' has no attribute 'LINEAR'
Could you please tell me how can I find the correct version, just like hou you solve this problem? Thank you very much!
